os: linux
dist: jammy
language: python
python:
  - "3.10.8"
services:
  - postgresql
env:
  - DB_NAME=postgres
  - DB_USER=postgres
  - DB_PASSWORD=postgres
before_install: 
  - sudo apt update
  - sudo apt upgrade -y
install:
  - pip install pytest pytest-postgresql ruff
  - pip install -r requirements-dev.txt
before_script:
  - psql -c 'create database postgres;' -U postgres
  - ruff --format=github --select=E9,F63,F7,F82 --target-version=py310 .
  - ruff --format=github --target-version=py310 .
script:
  - pytest