openapi: 3.0.0
info:
  title: Drone API
  description: An API to control a fleet of drones, to carry on medications.
  version: 1.0.0

paths:
  /:
    get:
      operationId: api.main.welcome
      summary: Returns a welcome message.
      description: Displays welcome message
      responses:
        '200':    # status code
          description: A JSON with Welcome message
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                    example: Welcome to Drone API
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not found
        '406':
          description: Not acceptable
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not acceptable
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Too many requests
        'default':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unexpected error
  /health:
    get:
      operationId: api.main.health
      summary: Returns a health status.
      description: Displays health status
      responses:
        '200':    # status code
          description: A JSON with health status
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                    example: OK
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not found
        '406':
          description: Not acceptable
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not acceptable
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Too many requests
        'default':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unexpected error
  /createdb:
    get:
      operationId: api.main.create_db
      tags:
      - db-helper
      summary: Creates a database per config settings
      description: Creates a database per config settings
      responses:
        200:
          description: Creates a database per config settings

