openapi: 3.0.0
info:
  title: Drone API
  description: An API to control a fleet of drones, to carry on medications.
  version: 1.0.0

components:
  schemas:
    Drone:
      type: object
      properties:
        serial_number:
          type: string
          maxLength: 100
          pattern: "^[a-zA-Z0-9]*$"
        model:
          type: string
          enum:
            - Lightweight
            - Middleweight
            - Cruiserweight
            - Heavyweight
        battery_capacity:
          type: integer
          minimum: 0
          maximum: 100
      required:
        - serial_number
        - model
    DroneResponse:
      type: object
      properties:
        status:
          type: string
        data:
          type: object
          properties:
            serial_number:
              type: string
              maxLength: 100
              pattern: "^[a-zA-Z0-9]*$"
            model:
              type: string
              enum:
                - Lightweight
                - Middleweight
                - Cruiserweight
                - Heavyweight
            weight:
              type: integer
              minimum: 200
              maximum: 500
            battery_capacity:
              type: integer
              minimum: 0
              maximum: 100
            status:
              type: string
              enum:
              - IDLE
              - LOADING
              - LOADED
              - DELIVERING
              - DELIVERED
              - RETURNING

paths:
  /:
    get:
      operationId: api.main.welcome
      summary: Returns a welcome message.
      description: Displays welcome message
      responses:
        '200':    # status code
          description: A JSON with Welcome message
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                    example: Welcome to Drone API
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not found
        '406':
          description: Not acceptable
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not acceptable
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Too many requests
        'default':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unexpected error
  /health:
    get:
      operationId: api.main.health
      summary: Returns a health status.
      description: Displays health status
      responses:
        '200':    # status code
          description: A JSON with health status
          content:
            application/json:
              schema: 
                type: object
                properties:
                  status:
                    type: string
                    example: OK
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not found
        '406':
          description: Not acceptable
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not acceptable
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Too many requests
        'default':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unexpected error
  /create_db:
    get:
      operationId: api.main.create_db
      summary: Creates the database.
      description: Creates the database
      responses:
        '200':    # status code
          description: A JSON with database created
          content:
            application/json:
              schema: 
                type: object
                properties:
                  message:
                    type: string
                    example: Database created
        '404':
          description: Not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not found
        '406':
          description: Not acceptable
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not acceptable
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Too many requests
        'default':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unexpected error

  /register_drone:
    post:
      operationId: api.drone.register_drone
      summary: Register a drone.
      description: Register a drone
      requestBody:
        required: true
        content:
          application/json:
             schema:
              $ref: '#/components/schemas/Drone'
      responses:
        '201':
          description: Drone registered
          content:
            application/json:
             schema:
              $ref: '#/components/schemas/DroneResponse'


  /drone/{id}:
    get:
      operationId: api.drone.get_drone
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            minimum: 1
          description: The drone ID
      responses:
        '200':
          description: Drone found
          content:
            application/json:
             schema:
              $ref: '#/components/schemas/DroneResponse'
        '404':
          description: Drone not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Drone not found
        '406':
          description: Not acceptable
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Not acceptable
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Too many requests
        'default':
          description: Unexpected error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Unexpected error
