name: Python test

on:
  push:
    branches: [ master, develop ]
    tags: [ 'v*.*.*' ]

jobs:
  build:

    runs-on: ubuntu-latest


    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.10.8
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi

      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --format=github --select=E9,F63,F7,F82 --target-version=py310 .
          # default set of ruff rules with GitHub Annotations
          ruff --format=github --target-version=py310 .

      - name: Create images folder
        run: |
          #Use mkdir to create folder
          mkdir -p public/images

      - name: Test with pytest
        run: |
          pytest
        env:
          DB_NAME: postgres

